name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # <-- 터보 affected 비교를 위해 필수

      - name: Enable Corepack (Yarn Berry)
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run affected tests
        run: npx turbo run test --filter=origin/main...HEAD

      - name: Run affected builds
        run: npx turbo run build --filter=origin/main...HEAD
